apiVersion: v1
kind: Service
metadata:
    namespace: ors
    name: mds
    labels:
        app: mds
spec:
  selector:
    app: mds
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
