apiVersion: v1
kind: Pod
metadata:
  namespace: ors
  name: mongo
  labels:
    app: mongo
spec:
  containers:
  - name: mongo
    image: mongo
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: mongoadmin
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: mongotest
