apiVersion: v1
kind: Service
metadata:
  namespace: ors
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
