apiVersion: v1
kind: Service
metadata:
    namespace: ors
    name: stardog
    labels:
        app: stardog
spec:
  selector:
    app: stardog
  ports:
  - protocol: TCP
    port: 5820
    targetPort: 5820
  type: ClusterIP
