apiVersion: v1
kind: Namespace
metadata:
    name: ors
    labels:
        app: ors
---
apiVersion: v1
kind: Pod
metadata:
  namespace: ors
  name: mongo
  labels:
    app: mongo
spec:
  containers:
  - name: mongo
    image: mongo
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: mongoadmin
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: mongotest
---
apiVersion: v1
kind: Service
metadata:
  namespace: ors
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  namespace: ors
  name: stardog
  labels:
    app: stardog
spec:
  containers:
  - name: stardog
    image: stardog/stardog
---
apiVersion: v1
kind: Service
metadata:
    namespace: ors
    name: stardog
    labels:
        app: stardog
spec:
  selector:
    app: stardog
  ports:
  - protocol: TCP
    port: 5820
    targetPort: 5820
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
    namespace: ors
    name: mds
    labels:
        app: mds
spec:
    containers:
    - name: mds
      image: jackofsum/mds
---
apiVersion: v1
kind: Service

